"""Where each firm publishes its Pillar 3 PDFs. Verified 6 September 2026 (docs section 12.4).

Fields
  entity    id in data/entities.csv
  page      listing page(s) whose HTML (or embedded JSON) carries the PDF links
  match     regex tested against the URL-decoded absolute link (case-insensitive)
  exclude   regex that rejects a link (other group entities, glossaries, remuneration)
  year_end  "MM-DD" financial year end, used to infer a period from a bare year in the URL
  nsm       also poll the FCA National Storage Mechanism by LEI (default True)
  kind      html (default) | nsm (site blocked, NSM only) | browser (site blocked and not on NSM;
            collected on the Mac with a real browser by the review skill) | pattern (no listing page:
            `urls` are templates tried for the last six fiscal quarters with {year} {yy} {q} {qend})
  template  km1 (default) | us_capital (US Pillar 3 report) | us_lcr (US LCR public disclosure)
  note      free text for the maintainer
"""
from __future__ import annotations

P3 = r"pillar[-_ %]?(?:3|iii)"

HKMA = "https://vpr.hkma.gov.hk/eng/regulatory-resources/registers/register-of-ais-and-lros/info/"
# The HKMA public register carries every Hong Kong authorised institution's disclosure documents
# at a stable address, which beats three bank sites that each redesign on their own schedule.
# fd_int is the interim disclosure statement: the March and September ones carry KM1, the June
# and December ones are the shorter financial disclosures and do not. A new HK bank is one id away.
HKMA_KM1 = r"/fd_int/fd_int_(?:03|09)\d\d_eng\.pdf"


LOCATORS: list[dict] = [
    # ---- UK large banks -------------------------------------------------
    dict(entity="barclays", page="https://home.barclays/investor-relations/reports-and-events/financial-results/",
         match=r"(Barclays[ _-]PLC[ _-]Pillar[ _-]?3|BPLC-Pillar-3)", exclude=r"Bank|BBPLC|BBUK|BBI|Capital Securities|Terms|Remuneration|T-and-C"),
    dict(entity="barclays", page="https://home.barclays/investor-relations/reports-and-events/annual-reports/",
         match=r"(Barclays[ _-]PLC[ _-]Pillar[ _-]?3|BPLC-Pillar-3)", exclude=r"Bank|BBPLC|BBUK|BBI|Capital Securities|Terms|Remuneration|T-and-C",
         note="year-end reports back to 2016"),
    dict(entity="barclays-bank", page="https://home.barclays/investor-relations/reports-and-events/financial-results/",
         match=r"(Barclays[ _-]Bank[ _-]PLC[ _-]Pillar[ _-]?3|BBPLC-Pillar-3)", exclude=r"UK PLC|UK-PLC|BBUK|Ireland|BBI|Terms|Remuneration|T-and-C"),
    dict(entity="barclays-bank", page="https://home.barclays/investor-relations/reports-and-events/annual-reports/",
         match=r"(Barclays[ _-]Bank[ _-]PLC[ _-]Pillar[ _-]?3|BBPLC-Pillar-3)", exclude=r"UK PLC|UK-PLC|BBUK|Ireland|BBI|Terms|Remuneration|T-and-C"),
    dict(entity="barclays-bank-uk", page="https://home.barclays/investor-relations/reports-and-events/financial-results/",
         match=r"(Barclays[ _-]Bank[ _-]UK[ _-]PLC[ _-]Pillar[ _-]?3|BBUKPLC-Pillar-3)", exclude=r"Terms|Remuneration|T-and-C"),
    dict(entity="barclays-bank-uk", page="https://home.barclays/investor-relations/reports-and-events/annual-reports/",
         match=r"(Barclays[ _-]Bank[ _-]UK[ _-]PLC[ _-]Pillar[ _-]?3|BBUKPLC-Pillar-3)", exclude=r"Terms|Remuneration|T-and-C"),
    dict(entity="hsbc-holdings", page="https://www.hsbc.com/investors/results-and-announcements/all-reporting/group",
         match=r"hsbc-holdings-plc/.*pillar-3-disclosures-at-.*\.pdf", exclude=r"chinese|glossary|-cn\.pdf"),
    dict(entity="hsbc-uk", page="https://www.hsbc.com/investors/results-and-announcements/all-reporting/subsidiaries",
         match=r"hsbc-uk-bank-plc/.*pillar-3.*\.pdf"),
    dict(entity="hsbc-bank", page="https://www.hsbc.com/investors/results-and-announcements/all-reporting/subsidiaries",
         match=r"hsbc-bank-plc/.*pillar-3.*\.pdf"),
    dict(entity="lloyds-banking-group", page="https://www.lloydsbankinggroup.com/investors/financial-performance/",
         match=P3, kind="browser", note="Akamai bot manager; not on the NSM"),
    dict(entity="lloyds-bank", page="https://www.lloydsbankinggroup.com/investors/financial-performance/",
         match=r"lloyds-bank-plc.*" + P3, kind="browser"),
    dict(entity="bank-of-scotland", page="https://www.lloydsbankinggroup.com/investors/financial-performance/",
         match=r"bank-of-scotland.*" + P3, kind="browser"),
    dict(entity="lloyds-bank-corporate-markets", page="https://www.lloydsbankinggroup.com/investors/financial-performance/",
         match=r"(?:lbcm|corporate-markets).*" + P3, kind="browser",
         note="same Akamai block as the rest of the group site"),
    dict(entity="natwest-group", page="https://investors.natwestgroup.com/results-centre",
         match=r"results-center/.*/nwg-.*pillar-3.*\.pdf", exclude=r"appendix"),
    dict(entity="natwest-bank", page="https://investors.natwestgroup.com/results-centre",
         match=r"results-center/.*/nwb-.*pillar-?3.*\.pdf", exclude=r"appendix"),
    dict(entity="natwest-markets", page="https://investors.natwestgroup.com/results-centre",
         match=r"results-center/.*/(?:nwm|natwest-markets).*pillar-?3.*\.pdf", exclude=r"appendix"),
    dict(entity="standard-chartered", page="https://www.sc.com/en/investors/financial-results/",
         match=r"sc\.com/.*" + P3 + r".*\.pdf", exclude=r"gsib|remuneration|g-sib"),
    dict(entity="santander-uk", page="https://www.santander.co.uk/about-santander/investor-relations/santander-uk-group-holdings-plc",
         match=r"(acrmd|additional[ _-]capital)", exclude=r"remuneration|q1_16|2017_"),
    # ---- UK mid-size ----------------------------------------------------
    dict(entity="virgin-money-uk", page="https://www.virginmoneyukplc.com/investor-relations/results-and-reporting/financial-results/",
         match=r"downloads/pdf/.*" + P3 + r".*\.pdf", exclude=r"cbplc|clydesdale", year_end="09-30"),
    dict(entity="clydesdale-bank", page="https://www.virginmoneyukplc.com/investor-relations/results-and-reporting/financial-results/",
         match=r"downloads/pdf/(cbplc|clydesdale).*" + P3 + r".*\.pdf", year_end="09-30"),
    dict(entity="tsb", page="https://www.tsb.co.uk/investors/regulatory-news-service.html",
         match=r"tsb-public/.*" + P3 + r".*\.pdf", exclude=r"quarterly", note="quarterly documents carry OV1 and LCR only, no KM1"),
    dict(entity="co-operative-bank", page="https://www.co-operativebank.co.uk/about-us/investor-relations/financial-results/",
         match=r"investorrelations/.*" + P3 + r".*\.pdf"),
    dict(entity="metro-bank", page="https://www.metrobankonline.co.uk/investor-relations/",
         match=r"globalassets/.*" + P3 + r".*\.pdf", exclude=r"interactive"),
    dict(entity="osb-group", page="https://www.osb.co.uk/investors/pillar-3-disclosure",
         match=r"/media/.*(pillar-3|disclosure).*\.pdf", exclude=r"charter|ccfs"),
    dict(entity="shawbrook", page="https://www.shawbrook.co.uk/about-us/investors/results-centre/",
         match=r"/media/.*" + P3 + r".*\.pdf"),
    dict(entity="aldermore", page="https://www.aldermore.co.uk/investors/results-and-presentations/",
         match=r"/media/.*" + P3 + r".*\.pdf", year_end="06-30", note="year end moved to 31 December from 2024"),
    dict(entity="close-brothers", page="https://www.closebrothers.com/investor-relations/results-reports-and-presentations",
         match=P3, kind="nsm", year_end="07-31", note="JavaScript shell, PDFs 401; files on the NSM"),
    dict(entity="paragon", page="https://www.paragonbankinggroup.co.uk/investor-relations/results-reports-and-presentations",
         match=P3, kind="nsm", year_end="09-30", note="Cloudflare; files on the NSM"),
    dict(entity="secure-trust-bank", page="https://www.securetrustbank.com/investor-relations/investors/results-reports-and-presentations/",
         match=r"document-library/pillar-3", note="extension-less document URLs"),
    dict(entity="vanquis", page="https://www.vanquis.com/investors/results-reports-presentations/",
         match=r"wp-content/uploads/.*" + P3 + r".*\.pdf"),
    dict(entity="investec", page="https://www.investec.com/en_gb/welcome-to-investec/about-us/investor-relations.html",
         match=P3, kind="browser", year_end="03-31", note="Cloudflare on pages"),
    dict(entity="monzo", page="https://monzo.com/annual-report",
         match=r"(Monzo-MBL-Pillar-3|monzo-pillar-3).*\.pdf", year_end="03-31", note="MBL = Monzo Bank Limited; MBHG = group"),
    dict(entity="starling", page="https://www.starlingbank.com/investors/",
         match=P3 + r".*\.pdf", year_end="03-31"),
    dict(entity="handelsbanken-plc", page="https://www.handelsbanken.co.uk/en/about-us/financial-information",
         match=P3, kind="browser", note="extension-less document ids; check by hand"),
    dict(entity="goldman-sachs-international-bank", page="https://www.goldmansachs.com/investor-relations/financials/subsidiary-financial-info/gsib/",
         match=P3 + r".*\.pdf", kind="browser", note="Pillar 3 PDFs not linked in the page HTML"),
    dict(entity="smbc-bank-international", page="https://www.smbcgroup.com/emea/about/Notices-and-reporting",
         match=r"getmedia/[0-9a-f-]+/(?:SMBC[ _-]?BI[^/]*Pillar[ _-]?3|Pillar[ _-]?3[^/]*SMBC[ _-]?BI)[^/]*\.pdf",
         exclude=r"SMBCE|Nikko|SMBC[ _-]?EU|SMBCDP", year_end="03-31",
         note="one EMEA notices page carries every SMBC entity; SMBC-BI marks the UK plc"),
    dict(entity="credit-agricole-cib", page="https://www.ca-cib.com/en/document-search?keyword=pilier%203",
         match=r"sites/default/files/[0-9-]+/(?:EN_)?Pil(?:ier|lar)[ _]3[ _]CACIB[^/]*\.pdf", exclude=r"UAE|Onshore",
         note="the default document list is rendered client side and carries no Pillar 3; the keyword query "
              "is served whole. Quarterlies are financial reviews with OV1 and EU-LIQ1 but no KM1; the "
              "half-year carries the capital position as a simplified table, so it needs the reviewer"),
    dict(entity="nbk-international", page="https://www.nbk.com/london/disclosures.html",
         match=r"dam/jcr:[0-9a-f-]+/Pillar_III_Disclosures\.pdf",
         note="single stable URL replaced in place each year; the group's Basel III files on the Kuwait investor page are a different entity"),
    # ---- building societies ---------------------------------------------
    dict(entity="nationwide", page="https://www.nationwide.co.uk/about-us/governance-reports-and-results/results-and-accounts",
         match=r"results-and-accounts/.*pillar-3-disclosures.*\.pdf", year_end="04-04"),
    dict(entity="yorkshire-bs", page="https://www.ybs.co.uk/your-society/financial-results",
         match=r"/documents/d/ybs/.*pillar-3", note="extension-less document URLs, slug changes yearly"),
    dict(entity="coventry-bs", page="https://www.coventrybuildingsociety.co.uk/member/financial-results.html",
         match=r"financial-results/.*Pillar-3.*\.pdf"),
    dict(entity="skipton-bs", page="https://www.skipton.co.uk/about-us/pillar-3-disclosure",
         match=r"pillar-3-disclosures/.*\.pdf"),
    dict(entity="leeds-bs", page="https://www.leedsbuildingsociety.co.uk/your-society/financial-results/",
         match=P3 + r".*\.pdf", exclude=r"\.jpg|covers"),
    dict(entity="principality-bs", page="https://www.principality.co.uk/home/corporate-governance/financial-reports",
         match=r"getmedia/.*" + P3 + r".*\.pdf"),
    dict(entity="west-brom-bs", page="https://www.westbrom.co.uk/about-us/investor-relations",
         match=r"pillar-3-capital-disclosures.*\.pdf", year_end="03-31", kind="browser", note="document list now rendered by script"),
    dict(entity="nottingham-bs", page="https://www.thenottingham.com/about-us/accounts-and-statements",
         match=r"/media/.*" + P3 + r".*\.pdf"),
    dict(entity="cumberland-bs", page="https://www.cumberland.co.uk/about/results-archive",
         match=r"cumberland-pillar-3.*\.pdf", year_end="03-31"),
    dict(entity="darlington-bs", page="https://www.darlington.co.uk/who-we-are/corporate-governance/key-society-documents/",
         match=r"wp-content/uploads/.*" + P3 + r".*\.pdf"),
    dict(entity="melton-bs", page="https://www.themelton.co.uk/about-us/corporate-information/pillar-3-disclosure/",
         match=r"tmbs-content/uploads/.*" + P3 + r".*\.pdf"),
    dict(entity="monmouthshire-bs", page="https://www.monbs.com/about-us/corporate-governance/",
         match=r"media\.monbs\.com/.*pillar-3", year_end="04-30", note="one URL overwritten yearly"),
    dict(entity="family-bs", page="https://www.familybuildingsociety.co.uk/about-us/corporate-and-financial-information",
         match=r"pillar-3-risk-disclosure.*\.pdf"),
    dict(entity="newcastle-bs", page="https://newcastle.co.uk/about-us/financial-results/", match=P3 + r".*\.pdf", kind="browser"),
    dict(entity="saffron-bs", page="https://www.saffronbs.co.uk/about-us/", match=P3 + r".*\.pdf", kind="browser"),
    dict(entity="suffolk-bs", page="https://www.suffolkbuildingsociety.co.uk/about/governance/", match=P3 + r".*\.pdf", kind="browser"),
    dict(entity="progressive-bs", page="https://theprogressive.com/about-us/your-society", match=P3 + r".*\.pdf", kind="browser"),
    dict(entity="leek-bs", page="https://www.leekbs.co.uk/about-us/", match=r"content/images/page/files/.*Pillar 3.*\.pdf", kind="browser"),
    dict(entity="hinckley-and-rugby-bs", page="https://www.hrbs.co.uk/the-society/governance/", match=P3 + r".*\.pdf", kind="browser",
         note="stopped publishing after 2023 under the small domestic deposit taker regime"),
    dict(entity="furness-bs", page="https://www.furnessbs.co.uk/about-us/", match=P3 + r".*\.pdf", kind="browser"),
    # ---- UK subsidiaries of overseas banks -------------------------------
    dict(entity="al-rayan-bank", page="https://www.alrayanbank.co.uk/about-us/", match=P3 + r".*\.pdf", kind="browser"),
    dict(entity="gatehouse-bank", page="https://www.gatehousebank.com/about-us", match=P3 + r".*\.pdf", kind="browser"),
    dict(entity="sbi-uk", page="https://www.sbiuk.com/about-us/financial-information", match=P3 + r".*\.pdf", year_end="03-31", kind="browser",
         note="certificate hostname mismatch and script-rendered page"),
    dict(entity="icici-bank-uk", page="https://www.icicibank.co.uk/about-us/basel-disclosures",
         match=r"basel-pillar-3-disclosures.*\.pdf", year_end="03-31"),
    dict(entity="bank-of-china-uk", page="https://www.bankofchina.com/uk/en/aboutus/ab1/", match=P3 + r".*\.pdf", kind="browser"),
    dict(entity="icbc-london", page="https://www.icbclondon.com/en/about-us/", match=P3 + r".*\.pdf", kind="browser",
         note="london.icbc.com.cn no longer resolves; site address to be confirmed from the Mac"),
    dict(entity="bank-of-baroda-uk", page="https://www.bankofbarodauk.com/about-us",
         match=r"ukretail/pdf/disclosures-as-on.*\.pdf", year_end="03-31"),
    dict(entity="qib-uk", page="https://www.qib-uk.com/about-us/financial-information/", match=P3 + r".*\.pdf", kind="browser"),
    # ---- Australia and Canada (Basel KM1 in APS 330 / OSFI Pillar 3) --------
    dict(entity="anz", page="https://www.anz.com.au/shareholder/centre/reporting/", match=r"aps ?330|pillar-?3.*\.pdf",
         year_end="09-30", currency="AUD", note="files every APS 330 on the FCA NSM; site listing is script-rendered"),
    dict(entity="commonwealth-bank", page="https://www.commbank.com.au/about-us/investors/results.html",
         match=r"commbank-assets/.*pillar[- ]3.*\.pdf", year_end="06-30", currency="AUD"),
    dict(entity="nab", page="https://www.nab.com.au/about-us/shareholder-centre/regulatory-disclosures",
         match=P3 + r".*\.pdf", year_end="09-30", currency="AUD"),
    dict(entity="westpac", page="https://www.westpac.com.au/about-westpac/investor-centre/financial-information/regulatory-disclosures/",
         match=r"wbc-.*pillar-3-report.*\.pdf", year_end="09-30", currency="AUD"),
    dict(entity="macquarie-bank", page="https://www.macquarie.com/au/en/investors/regulatory-disclosures.html",
         match=r"disclosures/document/basel-3-pillar-3-capital", year_end="03-31", currency="AUD", kind="browser",
         note="document links resolve only in a browser session"),
    dict(entity="bendigo-and-adelaide-bank", page="https://www.bendigoadelaide.com.au/investor-centre/regulatory-disclosures/",
         match=P3 + r".*\.pdf", year_end="06-30", currency="AUD"),
    dict(entity="rbc", kind="pattern", urls=["https://www.rbc.com/investor-relations/_assets-custom/pdf/{year}q{q}pillar3.pdf"],
         year_end="10-31", currency="CAD"),
    dict(entity="td-bank", kind="pattern", year_end="10-31", currency="CAD",
         urls=["https://www.td.com/content/dam/tdcom/canada/about-td/pdf/quarterly-results/{year}/q{q}/{year}-q{q}-supp-regulatory-disc-en.pdf",
               "https://www.td.com/content/dam/tdcom/canada/about-td/pdf/quarterly-results/{year}/q{q}/{year}-q{q}-supp-regulatory-disclosure-en.pdf"]),
    dict(entity="scotiabank", kind="pattern", year_end="10-31", currency="CAD",
         urls=["https://www.scotiabank.com/content/dam/scotiabank/corporate/quarterly-reports/{year}/q{q}/Q{q}{yy}_Supplementary_Regulatory_Capital_Disclosures-EN.pdf"]),
    dict(entity="bmo", kind="pattern", urls=["https://www.bmo.com/ir/qtrinfo/1/{year}-q{q}/SuppRegCapitalDisclosure_Q{q}{yy}.pdf"],
         year_end="10-31", currency="CAD", note="bmo.com drops connections from data-centre addresses; works from the Mac"),
    dict(entity="cibc", kind="pattern", year_end="10-31", currency="CAD",
         urls=["https://www.cibc.com/content/dam/cibc-public-assets/about-cibc/investor-relations/pdfs/quarterly-results/{year}/q{q}{yy}disclosure-en.pdf"]),
    dict(entity="national-bank-of-canada", page="https://www.nbc.ca/about-us/investors/quarterly-results.html",
         match=r"suppack-regulatory-capital-q\d-20\d\d\.pdf", year_end="10-31", currency="CAD"),
    # ---- Asia and Gulf ----------------------------------------------------
    # ---- German promotional banks: they file an Offenlegungsbericht, published in English as a Disclosure Report
    dict(entity="rentenbank", page="https://www.rentenbank.de/en/investor-relations/business-development/",
         match=r"documents/(?:publications/)?(?:Disclosure-Report|Offenlegung|EN_Offenlegung|FINAL_EN_Offenlegung)[^/]*\.pdf",
         currency="EUR", note="verified 7 Sep 2026; the group left the EBA Transparency Exercise after 2018"),
    # ---- Japan, Hong Kong: verified 7 September 2026 by following each group's own disclosure index
    dict(entity="mufg", page="https://www.mufg.jp/english/ir/report/basel3/index.html", kind="browser",
         match=r"/basel3/[\w-]+/pdf/mufg\d+_09_en\.pdf", year_end="03-31", currency="JPY",
         note="the index links a page per quarter; the group splits KM1 across single-table PDFs and _09_ is Key metrics"),
    dict(entity="smfg", page="https://www.smfg.co.jp/english/investor/financial/basel_3.html",
         match=r"/basel_3/\d+/\d+_fg_e_km101\.pdf", year_end="03-31", currency="JPY",
         note="km101 is KM1 capital metrics; km102 is the liquidity half"),
    dict(entity="mizuho", page="https://www.mizuhogroup.com/investors/financial-information/basel", kind="browser",
         match=r"basel.*\.pdf|pillar", year_end="03-31", currency="JPY", note="listing is script-rendered"),
    dict(entity="sumitomo-mitsui-trust", page="https://www.smth.jp/en/investors/financial_info/index.html", kind="browser",
         match=r"basel|pillar", year_end="03-31", currency="JPY"),
    dict(entity="hsbc-hong-kong", page="https://www.hsbc.com.hk/legal/regulatory-disclosures/",
         match=r"banking-disclosure-statement-[a-z]+-20\d\d\.pdf", currency="HKD",
         note="Hong Kong files a Banking Disclosure Statement rather than a Pillar 3 report"),
    dict(entity="bochk", page=HKMA + "100072", match=HKMA_KM1, currency="HKD",
         note="its own regulatory page never yielded a document; the register does"),
    dict(entity="standard-chartered-hk", page=HKMA + "100269", match=HKMA_KM1, currency="HKD",
         note="the sc.com/hk investor page carries the group PLC's Hong Kong listing announcements, "
              "not this subsidiary's disclosure statements"),
    dict(entity="dbs", page="https://www.dbs.com/investors/financials/pillar-3-disclosures",
         match=r"quarterly-financials/.*P3.*\.pdf", currency="SGD"),
    dict(entity="ocbc", page="https://www.ocbc.com/group/investors/investor-information.page",
         match=r"capital-and-regulatory-disclosures/pillar-3/20\d\d/", currency="SGD",
         note="verified 7 Sep 2026: the investor-information page lists every Pillar 3 PDF by year"),
    dict(entity="uob", page="https://www.uobgroup.com/investor-relations/financial/index.page", match=P3 + r".*\.pdf", currency="SGD", kind="browser"),
    dict(entity="first-abu-dhabi-bank", page="https://www.bankfab.com/en-ae/about-fab/investor-relations", match=r"(basel|pillar).*\.pdf", currency="AED", kind="browser"),
    dict(entity="emirates-nbd", page="https://www.emiratesnbd.com/en/investor-relations/basel-iii-pillar-3", match=r"(basel|pillar).*\.pdf", currency="AED", kind="browser"),
    dict(entity="adcb", page="https://www.adcb.com/en/about-us/investor-relations/basel-iii/", match=r"(basel|pillar).*\.pdf", currency="AED", kind="browser"),
    dict(entity="qnb", page="https://www.qnb.com/sites/qnb/qnbglobal/page/en/eninvestorrelations.html", match=r"(basel|pillar).*\.pdf", currency="QAR", kind="browser"),
]

# ---- United States: holding-company Pillar 3 reports and LCR disclosures ----------
LOCATORS += [
    dict(entity="wells-fargo", kind="pattern", template="us_capital", currency="USD",
         urls=["https://www.wellsfargo.com/assets/pdf/about/investor-relations/basel-disclosures/{year}-{qword}-quarter-pillar-3-disclosure.pdf"]),
    dict(entity="wells-fargo", kind="pattern", template="us_lcr", currency="USD",
         urls=["https://www.wellsfargo.com/assets/pdf/about/investor-relations/lcr-disclosures/{year}-{qword}-quarter-lcr-disclosure.pdf"]),
    dict(entity="bank-of-america", template="us_capital", currency="USD",
         page="https://investor.bankofamerica.com/regulatory-and-other-filings/basel-pillar-3-disclosures/pillar-3-regulatory-capital-disclosures",
         match=r"cloudfront\.net/.*pillar.?3.?disclosure.*\.pdf", exclude=r"europe|securities|merrill"),
    dict(entity="bank-of-america", template="us_lcr", currency="USD",
         page="https://investor.bankofamerica.com/regulatory-and-other-filings/basel-pillar-3-disclosures/pillar-3-regulatory-liquidity-disclosures",
         match=r"cloudfront\.net/.*liquidity.?coverage.?ratio.*\.pdf", exclude=r"nsfr|net.?stable"),
    dict(entity="northern-trust", kind="pattern", template="us_capital", currency="USD",
         urls=["https://www.northerntrust.com/content/dam/northerntrust/pws/nt/documents/earnings/pillar-3/northern-trust-pillar3-northern-trust-corporation-{year}Q{q}.pdf",
               "https://www.northerntrust.com/content/dam/northerntrust/pws/nt/documents/earnings/pillar-3/northern-trust-pillar-3-northern-trust-corporation-{year}Q{q}.pdf"]),
    dict(entity="goldman-sachs", kind="browser", template="us_lcr", currency="USD",
         page="https://www.goldmansachs.com/investor-relations/financials/other-information", match=r"liquidity-coverage-ratio.*\.pdf",
         note="PDF URLs return a challenge page to scripts; capital ratios come from EDGAR XBRL"),
    dict(entity="morgan-stanley", kind="pattern", template="us_lcr", currency="USD",
         urls=["https://www.morganstanley.com/content/dam/msdotcom/en/about-us-ir/pdf/US_LCR_Disclosures_{mm}_{dd}_{yy}.pdf"],
         note="capital ratios come from EDGAR XBRL; the Pillar 3 report states them only as excess over minimum"),
    dict(entity="bny", kind="pattern", template="us_lcr", currency="USD",
         urls=["https://www.bny.com/assets/corporate/documents/pdf/investor-relations/liquidity-coverage-ratio-disclosure-{q}q{yy}.pdf"]),
    dict(entity="citigroup", kind="pattern", template="us_lcr", currency="USD",
         urls=["https://www.citigroup.com/rcs/citigpa/storage/public/lcr{yymmdd}.pdf"]),
    dict(entity="citigroup", kind="pattern", template="us_capital", currency="USD",
         urls=["https://www.citigroup.com/rcs/citigpa/storage/public/c-basel-iii-adv-approach-{mm}-{dd}-{year}.pdf",
               "https://www.citigroup.com/rcs/citigpa/storage/public/c-baseI-iii-adv-approach-{mm}-{dd}-{year}.pdf"]),
    dict(entity="northern-trust", kind="pattern", template="us_lcr", currency="USD",
         urls=["https://www.northerntrust.com/content/dam/northerntrust/pws/nt/documents/earnings/disclosures/liquidity-coverage-ratio-disclosure-{q}q{year}.pdf"]),
    dict(entity="jpmorgan-chase", kind="browser", template="us_capital", currency="USD",
         page="https://jpmorganchaseco.gcs-web.com/ir/sec-other-filings/basel-pillar-3-us-lcr-disclosures", match=r"static-files",
         text=r"pillar ?3|pillar iii|liquidity coverage|\bLCR\b", exclude=r"financial statement|securities llc|bank,? n\.?a\b|chase bank",
         note="listing blocks scripts; download addresses are opaque, so the link text picks the Pillar 3 and LCR reports"),
    dict(entity="citigroup", kind="browser", template="us_capital", currency="USD",
         page="https://www.citigroup.com/global/investors", match=r"rcs/citigpa/storage/public/.*(basel|pillar).*\.pdf"),
    dict(entity="state-street", kind="browser", template="us_capital", currency="USD",
         page="https://investors.statestreet.com/filings-and-reports/supplemental-public-disclosure-of-basel-iii-regulatory-capital/default.aspx", match=r"q4cdn\.com/.*P3-Capital.*\.pdf"),
    dict(entity="goldman-sachs", kind="browser", template="us_capital", currency="USD",
         page="https://www.goldmansachs.com/investor-relations/financials/other-information", match=P3 + r".*\.pdf", note="CET1 and SLR also come from EDGAR XBRL"),
    dict(entity="ubs", kind="browser", currency="USD",
         page="https://www.ubs.com/global/en/investor-relations/financial-information/pillar-3-disclosures.html", match=P3 + r".*\.(?:pdf|html?)(?:\?|$)",
         exclude=r"gsib|g-sib|indicator|tlac|resolution|remuneration|pillar-3-disclosures\.html",
         note="UBS KM1 in the quarterly Pillar 3 report, lately published as a web page; the G-SIB indicators file is not it"),
]

COUNTRY_CCY = {"GB": "GBP", "US": "USD", "AU": "AUD", "CA": "CAD", "SG": "SGD", "HK": "HKD", "JP": "JPY",
               "AE": "AED", "QA": "QAR", "CH": "CHF", "IE": "EUR", "DE": "EUR", "FR": "EUR", "NL": "EUR",
               "ES": "EUR", "IT": "EUR", "BE": "EUR", "FI": "EUR", "AT": "EUR", "SE": "SEK", "DK": "DKK", "NO": "NOK"}


def by_entity() -> dict[str, dict]:
    return {l["entity"]: l for l in LOCATORS}
