"""Where each firm publishes its Pillar 3 PDFs. Verified 6 September 2026 (docs section 12.4).

Fields
  entity    id in data/entities.csv
  page      listing page(s) whose HTML (or embedded JSON) carries the PDF links
  match     regex tested against the URL-decoded absolute link (case-insensitive)
  exclude   regex that rejects a link (other group entities, glossaries, remuneration)
  year_end  "MM-DD" financial year end, used to infer a period from a bare year in the URL
  nsm       also poll the FCA National Storage Mechanism by LEI (default True)
  kind      html (default) | nsm (site blocked, NSM only) | browser (site blocked and not on NSM;
            collected on the Mac with a real browser by the review skill)
  note      free text for the maintainer
"""
from __future__ import annotations

P3 = r"pillar[-_ %]?(?:3|iii)"

LOCATORS: list[dict] = [
    # ---- UK large banks -------------------------------------------------
    dict(entity="barclays", page="https://home.barclays/investor-relations/reports-and-events/financial-results/",
         match=r"(Barclays PLC Pillar 3|BPLC-Pillar-3)", exclude=r"Bank|BBPLC|BBUK|BBI|Capital Securities"),
    dict(entity="barclays-bank", page="https://home.barclays/investor-relations/reports-and-events/financial-results/",
         match=r"(Barclays Bank PLC Pillar 3|BBPLC-Pillar-3)", exclude=r"UK PLC|BBUK|Ireland|BBI"),
    dict(entity="barclays-bank-uk", page="https://home.barclays/investor-relations/reports-and-events/financial-results/",
         match=r"(Barclays Bank UK PLC Pillar 3|BBUKPLC-Pillar-3)"),
    dict(entity="hsbc-holdings", page="https://www.hsbc.com/investors/results-and-announcements/all-reporting/group",
         match=r"hsbc-holdings-plc/.*pillar-3-disclosures-at-.*\.pdf", exclude=r"chinese|glossary|-cn\.pdf"),
    dict(entity="hsbc-uk", page="https://www.hsbc.com/investors/results-and-announcements/all-reporting/subsidiaries",
         match=r"hsbc-uk-bank-plc/.*pillar-3.*\.pdf"),
    dict(entity="hsbc-bank", page="https://www.hsbc.com/investors/results-and-announcements/all-reporting/subsidiaries",
         match=r"hsbc-bank-plc/.*pillar-3.*\.pdf"),
    dict(entity="lloyds-banking-group", page="https://www.lloydsbankinggroup.com/investors/financial-performance/",
         match=P3, kind="browser", note="Akamai bot manager; not on the NSM"),
    dict(entity="lloyds-bank", page="https://www.lloydsbankinggroup.com/investors/financial-performance/",
         match=r"lloyds-bank-plc.*" + P3, kind="browser"),
    dict(entity="bank-of-scotland", page="https://www.lloydsbankinggroup.com/investors/financial-performance/",
         match=r"bank-of-scotland.*" + P3, kind="browser"),
    dict(entity="natwest-group", page="https://investors.natwestgroup.com/results-centre",
         match=r"results-center/.*/nwg-.*pillar-3.*\.pdf", exclude=r"appendix"),
    dict(entity="natwest-bank", page="https://investors.natwestgroup.com/results-centre",
         match=r"results-center/.*/nwb-.*pillar-?3.*\.pdf", exclude=r"appendix"),
    dict(entity="standard-chartered", page="https://www.sc.com/en/investors/financial-results/",
         match=r"sc\.com/.*" + P3 + r".*\.pdf", exclude=r"gsib|remuneration|g-sib"),
    dict(entity="santander-uk", page="https://www.santander.co.uk/about-santander/investor-relations/santander-uk-group-holdings-plc",
         match=r"(acrmd|additional[ _-]capital)", exclude=r"remuneration|q1_16|2017_"),
    # ---- UK mid-size ----------------------------------------------------
    dict(entity="virgin-money-uk", page="https://www.virginmoneyukplc.com/investor-relations/results-and-reporting/financial-results/",
         match=r"downloads/pdf/.*" + P3 + r".*\.pdf", exclude=r"cbplc|clydesdale", year_end="09-30"),
    dict(entity="clydesdale-bank", page="https://www.virginmoneyukplc.com/investor-relations/results-and-reporting/financial-results/",
         match=r"downloads/pdf/(cbplc|clydesdale).*" + P3 + r".*\.pdf", year_end="09-30"),
    dict(entity="tsb", page="https://www.tsb.co.uk/investors/regulatory-news-service.html",
         match=r"tsb-public/.*" + P3 + r".*\.pdf", exclude=r"quarterly", note="quarterly documents carry OV1 and LCR only, no KM1"),
    dict(entity="co-operative-bank", page="https://www.co-operativebank.co.uk/about-us/investor-relations/financial-results/",
         match=r"investorrelations/.*" + P3 + r".*\.pdf"),
    dict(entity="metro-bank", page="https://www.metrobankonline.co.uk/investor-relations/",
         match=r"globalassets/.*" + P3 + r".*\.pdf", exclude=r"interactive"),
    dict(entity="osb-group", page="https://www.osb.co.uk/investors/pillar-3-disclosure",
         match=r"/media/.*(pillar-3|disclosure).*\.pdf", exclude=r"charter|ccfs"),
    dict(entity="shawbrook", page="https://www.shawbrook.co.uk/about-us/investors/results-centre/",
         match=r"/media/.*" + P3 + r".*\.pdf"),
    dict(entity="aldermore", page="https://www.aldermore.co.uk/investors/results-and-presentations/",
         match=r"/media/.*" + P3 + r".*\.pdf", year_end="06-30", note="year end moved to 31 December from 2024"),
    dict(entity="close-brothers", page="https://www.closebrothers.com/investor-relations/results-reports-and-presentations",
         match=P3, kind="nsm", year_end="07-31", note="JavaScript shell, PDFs 401; files on the NSM"),
    dict(entity="paragon", page="https://www.paragonbankinggroup.co.uk/investor-relations/results-reports-and-presentations",
         match=P3, kind="nsm", year_end="09-30", note="Cloudflare; files on the NSM"),
    dict(entity="secure-trust-bank", page="https://www.securetrustbank.com/investor-relations/investors/results-reports-and-presentations/",
         match=r"document-library/pillar-3", note="extension-less document URLs"),
    dict(entity="vanquis", page="https://www.vanquis.com/investors/results-reports-presentations/",
         match=r"wp-content/uploads/.*" + P3 + r".*\.pdf"),
    dict(entity="investec", page="https://www.investec.com/en_gb/welcome-to-investec/about-us/investor-relations.html",
         match=P3, kind="browser", year_end="03-31", note="Cloudflare on pages"),
    dict(entity="monzo", page="https://monzo.com/annual-report",
         match=r"(Monzo-MBL-Pillar-3|monzo-pillar-3).*\.pdf", year_end="03-31", note="MBL = Monzo Bank Limited; MBHG = group"),
    dict(entity="starling", page="https://www.starlingbank.com/investors/",
         match=P3 + r".*\.pdf", year_end="03-31"),
    dict(entity="handelsbanken-plc", page="https://www.handelsbanken.co.uk/en/about-us/financial-information",
         match=P3, kind="browser", note="extension-less document ids; check by hand"),
    dict(entity="goldman-sachs-international-bank", page="https://www.goldmansachs.com/investor-relations/financials/subsidiary-financial-info/gsib/",
         match=P3 + r".*\.pdf"),
    # ---- building societies ---------------------------------------------
    dict(entity="nationwide", page="https://www.nationwide.co.uk/about-us/governance-reports-and-results/results-and-accounts",
         match=r"results-and-accounts/.*pillar-3-disclosures.*\.pdf", year_end="04-04"),
    dict(entity="yorkshire-bs", page="https://www.ybs.co.uk/your-society/financial-results",
         match=r"/documents/d/ybs/.*pillar-3", note="extension-less document URLs, slug changes yearly"),
    dict(entity="coventry-bs", page="https://www.coventrybuildingsociety.co.uk/member/financial-results.html",
         match=r"financial-results/.*Pillar-3.*\.pdf"),
    dict(entity="skipton-bs", page="https://www.skipton.co.uk/about-us/pillar-3-disclosure",
         match=r"pillar-3-disclosures/.*\.pdf"),
    dict(entity="leeds-bs", page="https://www.leedsbuildingsociety.co.uk/your-society/financial-results/",
         match=P3 + r".*\.pdf", exclude=r"\.jpg|covers"),
    dict(entity="principality-bs", page="https://www.principality.co.uk/home/corporate-governance/financial-reports",
         match=r"getmedia/.*" + P3 + r".*\.pdf"),
    dict(entity="west-brom-bs", page="https://www.westbrom.co.uk/about-us/investor-relations",
         match=r"pillar-3-capital-disclosures.*\.pdf", year_end="03-31"),
    dict(entity="nottingham-bs", page="https://www.thenottingham.com/about-us/accounts-and-statements",
         match=r"/media/.*" + P3 + r".*\.pdf"),
    dict(entity="cumberland-bs", page="https://www.cumberland.co.uk/about/results-archive",
         match=r"cumberland-pillar-3.*\.pdf", year_end="03-31"),
    dict(entity="darlington-bs", page="https://www.darlington.co.uk/who-we-are/corporate-governance/key-society-documents/",
         match=r"wp-content/uploads/.*" + P3 + r".*\.pdf"),
    dict(entity="melton-bs", page="https://www.themelton.co.uk/about-us/corporate-information/pillar-3-disclosure/",
         match=r"tmbs-content/uploads/.*" + P3 + r".*\.pdf"),
    dict(entity="monmouthshire-bs", page="https://www.monbs.com/about-us/corporate-governance/",
         match=r"media\.monbs\.com/.*pillar-3", year_end="04-30", note="one URL overwritten yearly"),
    dict(entity="family-bs", page="https://www.familybuildingsociety.co.uk/about-us/corporate-and-financial-information",
         match=r"pillar-3-risk-disclosure.*\.pdf"),
    dict(entity="newcastle-bs", page="https://newcastle.co.uk/about-us/financial-results/", match=P3 + r".*\.pdf", kind="browser"),
    dict(entity="saffron-bs", page="https://www.saffronbs.co.uk/about-us/", match=P3 + r".*\.pdf", kind="browser"),
    dict(entity="suffolk-bs", page="https://www.suffolkbuildingsociety.co.uk/about/governance/", match=P3 + r".*\.pdf", kind="browser"),
    dict(entity="progressive-bs", page="https://theprogressive.com/about-us/your-society", match=P3 + r".*\.pdf", kind="browser"),
    dict(entity="leek-bs", page="https://www.leekbs.co.uk/about-us/", match=r"content/images/page/files/.*Pillar 3.*\.pdf", kind="browser"),
    dict(entity="hinckley-and-rugby-bs", page="https://www.hrbs.co.uk/the-society/governance/", match=P3 + r".*\.pdf", kind="browser",
         note="stopped publishing after 2023 under the small domestic deposit taker regime"),
    dict(entity="furness-bs", page="https://www.furnessbs.co.uk/about-us/", match=P3 + r".*\.pdf", kind="browser"),
    # ---- UK subsidiaries of overseas banks -------------------------------
    dict(entity="al-rayan-bank", page="https://www.alrayanbank.co.uk/about-us/reports-and-publications/", match=P3 + r".*\.pdf"),
    dict(entity="gatehouse-bank", page="https://gatehousebank.com/about-us/financial-information", match=P3 + r".*\.pdf"),
    dict(entity="sbi-uk", page="https://www.sbiuk.com/about-us/financial-information", match=P3 + r".*\.pdf", year_end="03-31"),
    dict(entity="icici-bank-uk", page="https://www.icicibank.co.uk/about-us/financials", match=P3 + r".*\.pdf", year_end="03-31"),
    dict(entity="bank-of-china-uk", page="https://www.bankofchina.com/uk/en/aboutus/ab1/", match=P3 + r".*\.pdf"),
    dict(entity="icbc-london", page="https://london.icbc.com.cn/en/", match=P3 + r".*\.pdf", kind="browser"),
    dict(entity="bank-of-baroda-uk", page="https://www.bankofbarodauk.com/about-us", match=P3 + r".*\.pdf", year_end="03-31"),
    dict(entity="qib-uk", page="https://www.qib-uk.com/about-us/financial-information/", match=P3 + r".*\.pdf"),
    # ---- Australia and Canada (Basel KM1 in APS 330 / OSFI Pillar 3) --------
    dict(entity="anz", page="https://www.anz.com/shareholder/centre/reporting/regulatory-disclosures/",
         match=r"aps ?330|pillar-?3.*\.pdf", year_end="09-30", currency="AUD"),
    dict(entity="commonwealth-bank", page="https://www.commbank.com.au/about-us/investors/regulatory-disclosures.html",
         match=P3 + r".*\.pdf", year_end="06-30", currency="AUD"),
    dict(entity="nab", page="https://www.nab.com.au/about-us/shareholder-centre/regulatory-disclosures",
         match=P3 + r".*\.pdf", year_end="09-30", currency="AUD"),
    dict(entity="westpac", page="https://www.westpac.com.au/about-westpac/investor-centre/regulatory-disclosures/",
         match=P3 + r".*\.pdf", year_end="09-30", currency="AUD"),
    dict(entity="macquarie-bank", page="https://www.macquarie.com/au/en/investors/regulatory-disclosures.html",
         match=P3 + r".*\.pdf", year_end="03-31", currency="AUD"),
    dict(entity="bendigo-and-adelaide-bank", page="https://www.bendigoadelaide.com.au/investor-centre/regulatory-disclosures/",
         match=P3 + r".*\.pdf", year_end="06-30", currency="AUD"),
    dict(entity="rbc", page="https://www.rbc.com/investor-relations/regulatory-capital-and-basel-pillar-3-disclosure.html",
         match=P3 + r".*\.pdf", year_end="10-31", currency="CAD"),
    dict(entity="td-bank", page="https://www.td.com/ca/en/about-td/for-investors/investor-relations/financial-information/regulatory-disclosures",
         match=P3 + r".*\.pdf", year_end="10-31", currency="CAD"),
    dict(entity="scotiabank", page="https://www.scotiabank.com/ca/en/about/investors-shareholders/regulatory-disclosures.html",
         match=P3 + r".*\.pdf", year_end="10-31", currency="CAD"),
    dict(entity="bmo", page="https://www.bmo.com/main/about-bmo/banking/investor-relations/regulatory-disclosures/",
         match=P3 + r".*\.pdf", year_end="10-31", currency="CAD"),
    dict(entity="cibc", page="https://www.cibc.com/en/about-cibc/investor-relations/regulatory-disclosures.html",
         match=P3 + r".*\.pdf", year_end="10-31", currency="CAD"),
    dict(entity="national-bank-of-canada", page="https://www.nbc.ca/about-us/investors/regulatory-disclosures.html",
         match=P3 + r".*\.pdf", year_end="10-31", currency="CAD"),
    # ---- Asia and Gulf ----------------------------------------------------
    dict(entity="dbs", page="https://www.dbs.com/investors/financials/pillar-3-disclosures", match=P3 + r".*\.pdf", currency="SGD"),
    dict(entity="ocbc", page="https://www.ocbc.com/group/investors/regulatory-disclosures", match=P3 + r".*\.pdf", currency="SGD"),
    dict(entity="uob", page="https://www.uobgroup.com/investor-relations/financial/index.page", match=P3 + r".*\.pdf", currency="SGD"),
    dict(entity="first-abu-dhabi-bank", page="https://www.bankfab.com/en-ae/about-fab/investor-relations/basel-iii-disclosures", match=r"(basel|pillar).*\.pdf", currency="AED"),
    dict(entity="emirates-nbd", page="https://www.emiratesnbd.com/en/investor-relations/basel-iii-pillar-3", match=r"(basel|pillar).*\.pdf", currency="AED"),
    dict(entity="adcb", page="https://www.adcb.com/en/about-us/investor-relations/basel-iii/", match=r"(basel|pillar).*\.pdf", currency="AED"),
    dict(entity="qnb", page="https://www.qnb.com/sites/qnb/qnbglobal/page/en/eninvestorrelations.html", match=r"(basel|pillar).*\.pdf", currency="QAR"),
]

COUNTRY_CCY = {"GB": "GBP", "US": "USD", "AU": "AUD", "CA": "CAD", "SG": "SGD", "HK": "HKD", "JP": "JPY",
               "AE": "AED", "QA": "QAR", "CH": "CHF", "IE": "EUR", "DE": "EUR", "FR": "EUR", "NL": "EUR",
               "ES": "EUR", "IT": "EUR", "BE": "EUR", "FI": "EUR", "AT": "EUR", "SE": "SEK", "DK": "DKK", "NO": "NOK"}


def by_entity() -> dict[str, dict]:
    return {l["entity"]: l for l in LOCATORS}
