"""Writes data/entities.csv for the release-one universe. Edit the list, re-run."""
import csv, re, collections
from pathlib import Path
ROOT = Path(__file__).resolve().parent.parent
U = [
("Barclays PLC","Barclays","GB","holding","uk","","213800LBQA1Y9L22JB70","BARC.L","","uk_large"),
("Barclays Bank PLC","Barclays Bank","GB","bank","uk","barclays","G5GSEF7VJP5I7OUK5573","","","uk_large"),
("Barclays Bank UK PLC","Barclays Bank UK","GB","bank","uk","barclays","","","","uk_large"),
("HSBC Holdings plc","HSBC Holdings","GB","holding","uk","","","HSBA.L","","uk_large"),
("HSBC UK Bank plc","HSBC UK","GB","bank","uk","hsbc-holdings","","","","uk_large"),
("HSBC Bank plc","HSBC Bank","GB","bank","uk","hsbc-holdings","","","","uk_large"),
("Lloyds Banking Group plc","Lloyds Banking Group","GB","holding","uk","","","LLOY.L","","uk_large"),
("Lloyds Bank plc","Lloyds Bank","GB","bank","uk","lloyds-banking-group","","","","uk_large"),
("Bank of Scotland plc","Bank of Scotland","GB","bank","uk","lloyds-banking-group","","","","uk_large"),
("NatWest Group plc","NatWest Group","GB","holding","uk","","2138005O9XJIJN4JPN90","NWG.L","","uk_large"),
("National Westminster Bank Plc","NatWest Bank","GB","bank","uk","natwest-group","","","","uk_large"),
("Standard Chartered PLC","Standard Chartered","GB","holding","uk","","U4LOSYZ7YG4W3S5F2G91","STAN.L","","uk_large"),
("Santander UK plc","Santander UK","GB","bank","uk","banco-santander","","","","uk_large"),
("Virgin Money UK PLC","Virgin Money UK","GB","bank","uk","nationwide","","","","uk_mid"),
("Clydesdale Bank PLC","Clydesdale Bank","GB","bank","uk","nationwide","","","","uk_mid"),
("TSB Bank plc","TSB","GB","bank","uk","banco-santander","","","","uk_mid"),
("The Co-operative Bank p.l.c.","Co-operative Bank","GB","bank","uk","coventry-bs","","","","uk_mid"),
("Metro Bank PLC","Metro Bank","GB","bank","uk","","","MTRO.L","","uk_mid"),
("OSB Group PLC","OSB Group","GB","holding","uk","","","OSB.L","","uk_mid"),
("Shawbrook Bank Limited","Shawbrook","GB","bank","uk","","","","","uk_mid"),
("Aldermore Bank PLC","Aldermore","GB","bank","uk","","","","","uk_mid"),
("Close Brothers Group plc","Close Brothers","GB","holding","uk","","","CBG.L","","uk_mid"),
("Paragon Banking Group PLC","Paragon","GB","holding","uk","","213800S1TDKIB1IUTS72","PAG.L","","uk_mid"),
("Secure Trust Bank PLC","Secure Trust Bank","GB","bank","uk","","","STB.L","","uk_small"),
("Vanquis Banking Group plc","Vanquis","GB","holding","uk","","","VANQ.L","","uk_small"),
("Investec plc","Investec","GB","holding","uk","","","INVP.L","","uk_mid"),
("Monzo Bank Limited","Monzo","GB","bank","uk","","","","","uk_small"),
("Starling Bank Limited","Starling","GB","bank","uk","","","","","uk_small"),
("Goldman Sachs International Bank","Goldman Sachs International Bank","GB","bank","uk","goldman-sachs","","","","uk_mid"),
("Handelsbanken plc","Handelsbanken plc","GB","bank","uk","svenska-handelsbanken","","","","uk_mid"),
("Nationwide Building Society","Nationwide","GB","building_society","uk","","549300XFX12G42QIKN82","","","uk_bs"),
("Yorkshire Building Society","Yorkshire BS","GB","building_society","uk","","","","","uk_bs"),
("Coventry Building Society","Coventry BS","GB","building_society","uk","","","","","uk_bs"),
("Skipton Building Society","Skipton BS","GB","building_society","uk","","66AGRETLUXS4YO5MUH35","","","uk_bs"),
("Leeds Building Society","Leeds BS","GB","building_society","uk","","","","","uk_bs"),
("Principality Building Society","Principality BS","GB","building_society","uk","","","","","uk_bs"),
("West Bromwich Building Society","West Brom BS","GB","building_society","uk","","","","","uk_bs"),
("Nottingham Building Society","Nottingham BS","GB","building_society","uk","","","","","uk_bs"),
("Newcastle Building Society","Newcastle BS","GB","building_society","uk","","","","","uk_bs"),
("Cumberland Building Society","Cumberland BS","GB","building_society","uk","","","","","uk_bs"),
("Leek Building Society","Leek BS","GB","building_society","uk","","","","","uk_bs"),
("Hinckley and Rugby Building Society","Hinckley and Rugby BS","GB","building_society","uk","","","","","uk_bs"),
("Darlington Building Society","Darlington BS","GB","building_society","uk","","","","","uk_bs"),
("Monmouthshire Building Society","Monmouthshire BS","GB","building_society","uk","","","","","uk_bs"),
("Saffron Building Society","Saffron BS","GB","building_society","uk","","","","","uk_bs"),
("Suffolk Building Society","Suffolk BS","GB","building_society","uk","","","","","uk_bs"),
("Furness Building Society","Furness BS","GB","building_society","uk","","","","","uk_bs"),
("Family Building Society","Family BS","GB","building_society","uk","","","","","uk_bs"),
("Progressive Building Society","Progressive BS","GB","building_society","uk","","","","","uk_bs"),
("Melton Mowbray Building Society","Melton BS","GB","building_society","uk","","","","","uk_bs"),
("Al Rayan Bank PLC","Al Rayan Bank","GB","subsidiary","uk","","","","","uk_small"),
("Gatehouse Bank plc","Gatehouse Bank","GB","subsidiary","uk","","","","","uk_small"),
("State Bank of India (UK) Limited","SBI UK","GB","subsidiary","uk","","","","","uk_small"),
("ICICI Bank UK PLC","ICICI Bank UK","GB","subsidiary","uk","","","","","uk_small"),
("Bank of China (UK) Limited","Bank of China UK","GB","subsidiary","uk","","","","","uk_small"),
("Industrial and Commercial Bank of China (London) plc","ICBC London","GB","subsidiary","uk","","","","","uk_small"),
("Bank of Baroda (UK) Limited","Bank of Baroda UK","GB","subsidiary","uk","","","","","uk_small"),
("Qatar Islamic Bank (UK) plc","QIB UK","GB","subsidiary","uk","","","","","uk_small"),
("Nordea Bank Abp","Nordea","FI","bank","eu","","","NDA-FI.HE","","eu_large"),
("Skandinaviska Enskilda Banken AB","SEB","SE","bank","eu","","","SEB-A.ST","","eu_large"),
("Swedbank AB","Swedbank","SE","bank","eu","","","SWED-A.ST","","eu_large"),
("Svenska Handelsbanken AB","Svenska Handelsbanken","SE","bank","eu","","","SHB-A.ST","","eu_large"),
("Danske Bank A/S","Danske Bank","DK","bank","eu","","","DANSKE.CO","","eu_large"),
("DNB Bank ASA","DNB","NO","bank","eu","","","DNB.OL","","eu_large"),
("OP Osuuskunta","OP Financial Group","FI","bank","eu","","","","","eu_large"),
("Nykredit Realkredit A/S","Nykredit","DK","bank","eu","","","","","eu_large"),
("ING Groep N.V.","ING","NL","holding","eu","","","INGA.AS","","eu_large"),
("Cooperatieve Rabobank U.A.","Rabobank","NL","bank","eu","","","","","eu_large"),
("ABN AMRO Bank N.V.","ABN AMRO","NL","bank","eu","","","ABN.AS","","eu_large"),
("Deutsche Bank AG","Deutsche Bank","DE","bank","eu","","","DBK.DE","","eu_large"),
("Commerzbank AG","Commerzbank","DE","bank","eu","","","CBK.DE","","eu_large"),
("Landesbank Hessen-Thueringen Girozentrale","Helaba","DE","bank","eu","","","","","eu_large"),
("Landesbank Baden-Wuerttemberg","LBBW","DE","bank","eu","","","","","eu_large"),
("Bayerische Landesbank","BayernLB","DE","bank","eu","","","","","eu_large"),
("DZ BANK AG Deutsche Zentral-Genossenschaftsbank","DZ Bank","DE","bank","eu","","","","","eu_large"),
("BNP Paribas","BNP Paribas","FR","bank","eu","","","BNP.PA","","eu_large"),
("Credit Agricole S.A.","Credit Agricole","FR","bank","eu","","","ACA.PA","","eu_large"),
("Societe Generale","Societe Generale","FR","bank","eu","","","GLE.PA","","eu_large"),
("Groupe BPCE","BPCE","FR","bank","eu","","","","","eu_large"),
("Confederation Nationale du Credit Mutuel","Credit Mutuel","FR","bank","eu","","","","","eu_large"),
("La Banque Postale","La Banque Postale","FR","bank","eu","","","","","eu_large"),
("KBC Group NV","KBC","BE","holding","eu","","","KBC.BR","","eu_large"),
("Belfius Bank SA/NV","Belfius","BE","bank","eu","","","","","eu_large"),
("Banco Santander, S.A.","Banco Santander","ES","bank","eu","","","SAN.MC","","eu_large"),
("Banco Bilbao Vizcaya Argentaria, S.A.","BBVA","ES","bank","eu","","","BBVA.MC","","eu_large"),
("CaixaBank, S.A.","CaixaBank","ES","bank","eu","","","CABK.MC","","eu_large"),
("Intesa Sanpaolo S.p.A.","Intesa Sanpaolo","IT","bank","eu","","","ISP.MI","","eu_large"),
("UniCredit S.p.A.","UniCredit","IT","bank","eu","","","UCG.MI","","eu_large"),
("Erste Group Bank AG","Erste Group","AT","bank","eu","","","EBS.VI","","eu_large"),
("Raiffeisen Bank International AG","Raiffeisen Bank International","AT","bank","eu","","","RBI.VI","","eu_large"),
("Bank of Ireland Group plc","Bank of Ireland","IE","holding","eu","","","BIRG.IR","","eu_large"),
("AIB Group plc","AIB","IE","holding","eu","","","A5G.IR","","eu_large"),
("Australia and New Zealand Banking Group Limited","ANZ","AU","bank","aus_can","","","ANZ.AX","","aus"),
("Commonwealth Bank of Australia","Commonwealth Bank","AU","bank","aus_can","","MSFSBD3QN1GSN7Q6C537","CBA.AX","","aus"),
("National Australia Bank Limited","NAB","AU","bank","aus_can","","","NAB.AX","","aus"),
("Westpac Banking Corporation","Westpac","AU","bank","aus_can","","EN5TNI6CI43VEPAMHL14","WBC.AX","","aus"),
("Macquarie Bank Limited","Macquarie Bank","AU","bank","aus_can","","","MQG.AX","","aus"),
("Bendigo and Adelaide Bank Limited","Bendigo and Adelaide Bank","AU","bank","aus_can","","","BEN.AX","","aus"),
("Royal Bank of Canada","RBC","CA","bank","aus_can","","","RY.TO","","can"),
("The Toronto-Dominion Bank","TD Bank","CA","bank","aus_can","","","TD.TO","","can"),
("The Bank of Nova Scotia","Scotiabank","CA","bank","aus_can","","","BNS.TO","","can"),
("Bank of Montreal","BMO","CA","bank","aus_can","","","BMO.TO","","can"),
("Canadian Imperial Bank of Commerce","CIBC","CA","bank","aus_can","","","CM.TO","","can"),
("National Bank of Canada","National Bank of Canada","CA","bank","aus_can","","","NA.TO","","can"),
("DBS Bank Ltd.","DBS","SG","bank","asia","","","D05.SI","","asia"),
("Oversea-Chinese Banking Corporation Limited","OCBC","SG","bank","asia","","","O39.SI","","asia"),
("United Overseas Bank Limited","UOB","SG","bank","asia","","","U11.SI","","asia"),
("The Hongkong and Shanghai Banking Corporation Limited","HSBC Hong Kong","HK","bank","asia","hsbc-holdings","","","","asia"),
("Bank of China (Hong Kong) Limited","BOCHK","HK","bank","asia","","","2388.HK","","asia"),
("Standard Chartered Bank (Hong Kong) Limited","Standard Chartered HK","HK","bank","asia","standard-chartered","","","","asia"),
("Mitsubishi UFJ Financial Group, Inc.","MUFG","JP","holding","asia","","","8306.T","","asia"),
("Sumitomo Mitsui Financial Group, Inc.","SMFG","JP","holding","asia","","","8316.T","","asia"),
("Mizuho Financial Group, Inc.","Mizuho","JP","holding","asia","","","8411.T","","asia"),
("Sumitomo Mitsui Trust Group, Inc.","Sumitomo Mitsui Trust","JP","holding","asia","","","8309.T","","asia"),
("Qatar National Bank (Q.P.S.C.)","QNB","QA","bank","gulf","","","QNBK.QA","","gulf"),
("First Abu Dhabi Bank P.J.S.C.","First Abu Dhabi Bank","AE","bank","gulf","","","FAB.AE","","gulf"),
("Emirates NBD Bank P.J.S.C.","Emirates NBD","AE","bank","gulf","","","EMIRATESNBD.AE","","gulf"),
("Abu Dhabi Commercial Bank P.J.S.C.","ADCB","AE","bank","gulf","","","ADCB.AE","","gulf"),
("Al Rajhi Banking and Investment Corporation","Al Rajhi Bank","SA","bank","gulf","","","1120.SR","","gulf"),
("The Saudi National Bank","Saudi National Bank","SA","bank","gulf","","","1180.SR","","gulf"),
("JPMorgan Chase & Co.","JPMorgan Chase","US","holding","us_ch","","","JPM","628","us"),
("Bank of America Corporation","Bank of America","US","holding","us_ch","","","BAC","3510","us"),
("Citigroup Inc.","Citigroup","US","holding","us_ch","","","C","7213","us"),
("Wells Fargo & Company","Wells Fargo","US","holding","us_ch","","","WFC","3511","us"),
("The Goldman Sachs Group, Inc.","Goldman Sachs","US","holding","us_ch","","","GS","33124","us"),
("Morgan Stanley","Morgan Stanley","US","holding","us_ch","","","MS","32992","us"),
("The Bank of New York Mellon Corporation","BNY","US","holding","us_ch","","","BK","639","us"),
("State Street Corporation","State Street","US","holding","us_ch","","","STT","14","us"),
("Northern Trust Corporation","Northern Trust","US","holding","us_ch","","","NTRS","913","us"),
("UBS Group AG","UBS","CH","holding","us_ch","","","UBSG.SW","","ch"),
]
def slug(s):
    s = s.lower().replace("&", "and"); return re.sub(r"[^a-z0-9]+", "-", s).strip("-")
out = ROOT / "data" / "entities.csv"
existing = {}
if out.exists():
    with out.open(newline="", encoding="utf-8") as f:
        existing = {r["id"]: r for r in csv.DictReader(f)}
rows, seen = [], set()
for name, short, cc, typ, reg, grp, lei, tick, cert, peer in U:
    sid = slug(short)
    lei = lei or existing.get(sid, {}).get("lei", "")  # keep LEIs resolved by research/resolve_leis.py
    assert sid not in seen, sid; seen.add(sid)
    rows.append(dict(id=sid, name=name, short_name=short, country=cc, type=typ, region=reg, group=grp, lei=lei, tickers=tick, fdic_cert=cert, peer_group=peer, active="true"))
ids = {r["id"] for r in rows}
for r in rows:
    assert not r["group"] or r["group"] in ids, ("group slug missing", r["group"])
with out.open("w", newline="", encoding="utf-8") as f:
    w = csv.DictWriter(f, fieldnames=list(rows[0].keys())); w.writeheader(); w.writerows(rows)
print(len(rows), "entities;", sum(1 for r in rows if r["lei"]), "with LEI;", dict(collections.Counter(r["region"] for r in rows)))
