#!/usr/bin/env bash
# Commit and push the answers a review run produced, and nothing else.
#
# The review and news skills used to end with a bare `git add`, `git commit`, `git push`. That is
# fine typed by a person on their own machine, and it is the one thing an unattended session is not
# allowed to do: an open-ended push is refused by the permission classifier, so the run finished,
# reported success and changed nothing. This script is the narrow version of that push - a fixed
# list of data files, never code, never the built site - so it can be allowed once, by name, and
# the routines can then run without anybody watching.
#
#   bash tools/push-data.sh "Review queue: 4 items resolved"
#
# Says what it did and exits 0 when there is nothing to push.
set -euo pipefail

MESSAGE="${1:?usage: push-data.sh <commit message>}"
cd "$(dirname "$0")/.."

# Built JSON is regenerated by whichever runner builds the site; a local copy must never be merged.
git checkout -- data/json 2>/dev/null || true
git pull --ff-only

# The answers, and only the answers.
git add data/facts.parquet data/documents.parquet data/runs.parquet data/events.parquet data/review 2>/dev/null || true
if git diff --cached --quiet; then
  echo "nothing to push"
  exit 0
fi
git status --short --cached | sed 's/^/  /'
git commit -q -m "$MESSAGE"

for wait in 2 4 8 16 0; do
  if git push; then
    echo "pushed: $MESSAGE"
    exit 0
  fi
  [ "$wait" -eq 0 ] && break
  echo "push failed, retrying in ${wait}s"
  sleep "$wait"
done
echo "push failed after four retries" >&2
exit 1
