#!/usr/bin/env bash
# Commit and push the answers a review run produced, and nothing else.
#
# The review and news skills used to end with a bare `git add`, `git commit`, `git push`. That is
# fine typed by a person on their own machine, and it is the one thing an unattended session is not
# allowed to do: an open-ended push is refused by the permission classifier, so the run finished,
# reported success and changed nothing. This script is the narrow version of that push - a fixed
# list of data files, never code, never the built site - so it can be allowed once, by name, and
# the routines can then run without anybody watching.
#
#   bash tools/push-data.sh "Review queue: 4 items resolved"
#
# Says what it did and exits 0 when there is nothing to push.
set -euo pipefail

MESSAGE="${1:?usage: push-data.sh <commit message>}"
cd "$(dirname "$0")/.."

# Built JSON is regenerated by whichever runner builds the site; a local copy must never be merged.
git checkout -- data/json 2>/dev/null || true

# The answers, and only the answers.
git add data/facts.parquet data/documents.parquet data/runs.parquet data/events.parquet data/review 2>/dev/null || true
if git diff --cached --quiet; then
  echo "nothing to push"
  exit 0
fi
git diff --cached --name-status | sed 's/^/  /'
git commit -q -m "$MESSAGE"

# Commit first, then integrate. Pulling with the answers still staged meant that any one of these
# files the pipeline had also written refused the fast-forward and ended the script, leaving a
# run's work staged and unpushed with nothing to say so. Committed work survives a failed merge.
git fetch --quiet origin main
if ! git -c pull.rebase=false pull --no-edit --quiet origin main; then
  echo "!! merged nothing: origin/main conflicts with this run's answers." >&2
  echo "!! the work is committed locally and safe; resolve and push by hand." >&2
  exit 1
fi

for wait in 2 4 8 16 0; do
  if git push; then
    echo "pushed: $MESSAGE"
    exit 0
  fi
  [ "$wait" -eq 0 ] && break
  echo "push failed, retrying in ${wait}s"
  sleep "$wait"
done
echo "push failed after four retries" >&2
exit 1
